# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/bf
    env:
      - CGO_ENABLED=0
  - main: ./cmd/bf
    id: lambda
    binary: bootstrap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    builds:
      - bifrost
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: linux
        format: tar.zst
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/ca-openapi.yml
  - id: lambda
    builds:
      - lambda
    name_template: "{{ .ProjectName }}_lambda_bundle_{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    format: zip
    wrap_in_directory: false
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

kos:
  - main: ./cmd/bf
    tags:
      - latest
      - "v{{ .Version }}"
    bare: true
    preserve_import_paths: true
    platforms:
      - linux/amd64
      - linux/arm64
