// Code generated by "stringer -linecomment -type=HeaderName"; DO NOT EDIT.

package asgard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeaderNameClientCertLeaf-0]
	_ = x[HeaderNameClientCert-1]
}

const _HeaderName_name = "X-Amzn-Mtls-Clientcert-LeafX-Amzn-Mtls-Clientcert"

var _HeaderName_index = [...]uint8{0, 27, 49}

func (i HeaderName) String() string {
	if i < 0 || i >= HeaderName(len(_HeaderName_index)-1) {
		return "HeaderName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HeaderName_name[_HeaderName_index[i]:_HeaderName_index[i+1]]
}
