openapi: 3.1.0
info:
  title: Bifrost Issuer
  description: >
    Bifrost Issuer issues certificates in response to certificate requests.
  contact:
    email: "ananth.b@qubecinema.com"
  license:
    name: "Mozilla Public License 2.0"
    identifier: "MPL-2.0"
  version: 1.10.0
security: []
paths:
  /namespaces:
    get:
      operationId: getNamespaces
      summary: Get a list of namespaces separated by newlines
      description: >
        Returns a list of namespace UUIDs that the issuer can issue certificates for.
        Namespace UUIDs are in hex format separated by newlines.
      responses:
        "200":
          description: List of namespaces.
          content:
            text/plain:
              schema:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                  type: string
                  format: uuid
                example: |
                  a3d129b3-ac16-4047-84cc-2e97447d31ea
                  d798e509-4d8c-455b-9814-2941df035b88
        "500":
          description: Internal Server Error.
          content:
            "text/plain":
              schema:
                type: string
  /{namespace}/issue:
    post:
      operationId: issueCertificate
      summary: Fetch a signed authentication certificate
      description: >
        Send an X.509 certificate request in PEM-encoded DER ASN.1 form (text/plain) or in
        DER ASN.1 form (application/octet-stream) and receive a signed certificate.
        Response content type mirrors the request's, unless the Accept header is set.
        A 403 response status code usually indicates
        that the client is using the wrong namespace UUID.
      parameters:
        - in: path
          name: namespace
          required: true
          description: Namespace UUID
          schema:
            type: string
            format: uuid
            example: 80485314-6c73-40ff-86c5-a5942a0f514f
      requestBody:
        content:
          "text/plain":
            schema:
              type: string
              pattern: '(-----BEGIN CERTIFICATE REQUEST-----(\n|\r|\r\n)([0-9a-zA-Z\+\/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+\/=]{1,63}(\n|\r|\r\n))?-----END CERTIFICATE REQUEST-----)'
              example: |
                -----BEGIN CERTIFICATE REQUEST-----
                MIIBGTCBwAIBADBeMS0wKwYDVQQDDCQwZjljMmFjNC1iZDdmLTU5MjMtYTc4NS1h
                OGJjNGQ4ZTI4MzExLTArBgNVBAoMJDgwNDg1MzE0LTZDNzMtNDBGRi04NkM1LUE1
                OTQyQTBGNTE0RjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIRKO/ou3QfVp5Ym
                aKyBForLVwIKx67Ts9q1tC2lyGXCTYhFAFpE8zBSq2NCWT1QaFBF4GBh4Ve4XNyH
                f/l+B/agADAKBggqhkjOPQQDAgNIADBFAiEAkabuKtTmT721rFNrdt8Cd9ukNHUf
                bJ261eOVJ1BBfz0CIGHvTy+4SbWHi3HGWt9L8dFBjscq4hAcguApp71QsFuA
                -----END CERTIFICATE REQUEST-----
          "application/octet-stream":
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Issue Certificate.
          content:
            "text/plain":
              schema:
                type: string
                example: |
                  -----BEGIN CERTIFICATE-----
                  MIIBcTCCARgCCQCdZeJe6CYRUDAKBggqhkjOPQQDAjBBMRQwEgYDVQQKDAtRdWJl
                  IENpbmVtYTESMBAGA1UECwwJUXViZSBXaXJlMRUwEwYDVQQDDAxCaWZyb3N0IENB
                  IDEwHhcNMjIxMDE0MTQxODIyWhcNMzIxMDExMTQxODIyWjBBMRQwEgYDVQQKDAtR
                  dWJlIENpbmVtYTESMBAGA1UECwwJUXViZSBXaXJlMRUwEwYDVQQDDAxCaWZyb3N0
                  IENBIDEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARUlAFwrEmyEt/WrufY3Lzb
                  HyBJ0J45GHNPHdQ4wPAcH7PbDqNmmycNi9TmvPNut1ShoGOQDzbLrshHYU4lqMYN
                  MAoGCCqGSM49BAMCA0cAMEQCIHowWM7sKmmBcJ19sWQf6lqUp2ywUhD5oXaf85Tu
                  +7+kAiBJaDq0BbnSdNk4P4fmt8WbDyYAmRJQnY5WirXslUGNpw==
                  -----END CERTIFICATE-----
            "application/octet-stream":
              schema:
                type: string
                format: binary
        "400":
          description: >
            Bad Request. Invalid certificate request.
          content:
            "text/plain":
              schema:
                type: string
        "403":
          description: >
            Forbidden. Incorrect certificate request namespace UUID.
          content:
            "text/plain":
              schema:
                type: string
        "405":
          description: Method Not Allowed.
          content:
            "text/plain":
              schema:
                type: string
        "415":
          description: Unsupported Media Type.
          content:
            "text/plain":
              schema:
                type: string
        "500":
          description: Internal Server Error.
          content:
            "text/plain":
              schema:
                type: string