name: Release 🚀

on:
  release:
    types:
      - created

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: web/package.json
          cache: 'npm'
          cache-dependency-path: |
            web/package-lock.json

      - name: Build
        shell: bash
        run: ./build.sh

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: bifrost
          path: |
            bin/*
            docs/ca-openapi.yml

      - name: Update Github release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          generate_release_notes: true
          files: |
            bin/*
            docs/ca-openapi.yml

  container_images:
    name: Push contaimer images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build bifrost image
        uses: redhat-actions/buildah-build@v2
        id: build_bf
        with:
          image: ${{ github.repository }}
          tags: >
            ${{ github.ref_name }}
            ${{ github.sha }}
            latest
          containerfiles: Containerfile
          oci: true
          archs: amd64, arm64

      - name: Push bifrost image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build_bf.outputs.image }}
          tags: ${{ steps.build_bf.outputs.tags }}
