name: Release 🚀

on:
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.21"
  NODE_VERSION: "20.7.0"

jobs:
  container_images:
    name: Push contaimer images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build bifrost image
        uses: redhat-actions/buildah-build@v2
        id: build_bf
        with:
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
          image: ${{ github.repository }}
          tags: >
            ${{ github.ref_name }}
            ${{ github.sha }}
            latest
          containerfiles: Containerfile
          oci: true
          archs: amd64  # , arm64
      - name: Push bifrost image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build_bf.outputs.image }}
          tags: ${{ steps.build_bf.outputs.tags }}
      - name: Build bifrost-authz image
        uses: redhat-actions/buildah-build@v2
        id: build_authz
        with:
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
          image: ${{ github.repository }}-authz
          tags: >
            ${{ github.ref_name }}
            ${{ github.sha }}
            latest
          containerfiles: Containerfile
          oci: true
          archs: amd64  # , arm64
          extra-args: |
            --target=authz
      - name: Push bifrost-authz image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build_authz.outputs.image }}
          tags: ${{ steps.build_authz.outputs.tags }}
      - name: Build bifrost-ca image
        uses: redhat-actions/buildah-build@v2
        id: build_ca
        with:
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
          image: ${{ github.repository }}-ca
          tags: >
            ${{ github.ref_name }}
            ${{ github.sha }}
            latest
          containerfiles: Containerfile
          oci: true
          archs: amd64  # , arm64
          extra-args: |
            --target=ca
      - name: Push bifrost-ca image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build_ca.outputs.image }}
          tags: ${{ steps.build_ca.outputs.tags }}
